### PR TITLE
Verify that no container in a ScyllaCluster Pod has restarted during e2e run

### LINKED ISSUE #2228: Verify there are no ScyllaDB container restarts during e2e runs
We should make sure no ScyllaDB container restarts during the e2e flow.

It's impact will be limited because ScyllaDB still runs within a supervisord :( but it will catch the cases where it gets killed by the liveness probes.

### PR DESCRIPTION
**Pull request by tnozicka**
**Description of your changes:**
This PR extends ScyllaCluster invariants in e2e to check that no container in the Pod has restarted which prevents cases that get stuck but sometimes get unstuck by failing liveness probe that unstucks the container.

**Which issue is resolved by this Pull Request:**
Resolves #2228 

### Requires
- [x] #2227

### CODE REVIEW

**Review by rzetelskik — APPROVED** [review]
lgtm
/assign zimnx

**Review by zimnx — APPROVED** [review]
/lgtm

**Pull request merged**
