### PR TITLE
Split Scylla Manager repair and backup task integration E2E tests

### PR DESCRIPTION
**Pull request by rzetelskik**
**Description of your changes:** This PR doesn't really bring any value in itself, but the test split allows for making the changes required for https://github.com/scylladb/scylla-operator/pull/1742 clearer, consequently making the review process easier.

**Which issue is resolved by this Pull Request:**
Prerequisite for https://github.com/scylladb/scylla-operator/pull/1742

/kind feature
/priority important-longterm
/cc

### CODE REVIEW

**Comment by rzetelskik** [comment]
> @rzetelskik: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> 
> Test name	Commit	Details	Required	Rerun command
> ci/prow/e2e-gke-parallel-clusterip	[3787e95](https://github.com/scylladb/scylla-operator/commit/3787e95132262333e39ac73b88b3ed5a34942bc0)	[link](https://prow.scylla-operator.scylladb.com/view/gs/scylla-operator-prow/pr-logs/pull/scylladb_scylla-operator/1891/pull-scylla-operator-master-e2e-gke-parallel-clusterip/1779805444886237184)	true	`/test e2e-gke-parallel-clusterip`

https://prow.scylla-operator.scylladb.com/view/gs/scylla-operator-prow/pr-logs/pull/scylladb_scylla-operator/1891/pull-scylla-operator-master-e2e-gke-parallel-clusterip/1779805444886237184#1:test-build-log.txt%3A948

Stuck on repair task deletion integration.
Controller issued task deletion:
```
2024-04-15T10:03:39.679445365Z I0415 10:03:39.621523       1 manager/sync.go:134] "Executing action" action="delete task \"4bd2d3d8-419c-4355-acf5-423666addec9\""
...
2024-04-15T10:03:39.679523675Z I0415 10:03:39.641612       1 manager/controller.go:148] "Hit conflict, will retry in a bit" Key="e2e-test-scyllacluster-8gx9r-w6wn4/basic-2mzvl" Error="Operation cannot be fulfilled on scyllaclusters.scylla.scylladb.com \"basic-2mzvl\": the object has been modified; please apply your changes to the latest version and try again"
```

Manager doesn't have related logs.
Wasn't propagated to status.
Working on it as part of https://github.com/scylladb/scylla-operator/pull/1850.

https://github.com/scylladb/scylla-operator/issues/1694#issuecomment-2056545655

> ci/prow/e2e-gke-parallel	[3787e95](https://github.com/scylladb/scylla-operator/commit/3787e95132262333e39ac73b88b3ed5a34942bc0)	[link](https://prow.scylla-operator.scylladb.com/view/gs/scylla-operator-prow/pr-logs/pull/scylladb_scylla-operator/1891/pull-scylla-operator-master-e2e-gke-parallel/1779805444856877056)	true	`/test e2e-gke-parallel`
> [Full PR test history](https://prow.scylla-operator.scylladb.com/pr-history?org=scylladb&repo=scylla-operator&pr=1891). [Your PR dashboard](https://prow.scylla-operator.scylladb.com/pr?query=is:pr+state:open+author:rzetelskik).

Stuck on repair task deletion integration.
Controller issued task deletion:
```
2024-04-15T10:03:20.346661594Z I0415 10:03:20.346612       1 manager/sync.go:134] "Executing action" action="delete task \"8c1bfa4c-e08c-41ab-b5ac-6dedd51b7ede\""
...
2024-04-15T10:03:20.434715683Z I0415 10:03:20.374406       1 manager/controller.go:148] "Hit conflict, will retry in a bit" Key="e2e-test-scyllacluster-2j6b9-r
gxkv/basic-qf87f" Error="Operation cannot be fulfilled on scyllaclusters.scylla.scylladb.com \"basic-qf87f\": the object has been modified; please apply your c
hanges to the latest version and try again"
```
Manager doesn't have related logs.
Wasn't propagated to status.
Working on it as part of https://github.com/scylladb/scylla-operator/pull/1850.

https://github.com/scylladb/scylla-operator/issues/1694#issuecomment-2056547274

/retest

**Comment by rzetelskik** [comment]
/retest e2e-gke-parallel-clusterip
cluster provisioning failed

**Comment by rzetelskik** [comment]
/test e2e-gke-parallel-clusterip
cluster provisioning failed

**Review by zimnx — APPROVED** [review]
/lgtm

**Pull request merged**
