### PR TITLE
[v1.15] Pin image tags to v1.15

### PR DESCRIPTION
**Pull request by zimnx**
In preparation for v1.15, manifest image was pinned to 1.15.

### CODE REVIEW

**Review by rzetelskik — APPROVED** [review]
/lgtm

**Comment by tnozicka** [comment]
/hold 
the docs substitutions need to be also pinned
https://github.com/scylladb/scylla-operator/blob/v1.15/docs/source/conf.py#L58

**Comment by tnozicka** [comment]
/hold cancel
(this will be harder with sphinx-multiversion)

**Comment by tnozicka** [comment]
filed #2204 to track the manifest versioning

**Pull request merged**
