### PR TITLE
Update manager to 3.2.6 and require it for v1.12

### PR DESCRIPTION
**Pull request by tnozicka**
**Description of your changes:**
This PR updates manager version i our manifests and CI to from 3.2.5 to 3.2.6 which fixes TLS and other issues. Given the restore procedure was broken with TLS and manager 3.2.5, we set 3.2.6 as the minimal version as well.

**Which issue is resolved by this Pull Request:**
Resolves #

### CODE REVIEW

**Review by rzetelskik — APPROVED** [review]
lgtm
/assign zimnx

**Review by zimnx — APPROVED** [review]
/lgtm

**Comment by tnozicka** [comment]
https://github.com/scylladb/scylla-operator/issues/1694#issuecomment-1983400091
/retest

**Comment by tnozicka** [comment]
that might be a problem, I don't think requiring it retrospectively for v1.11 would be good. if it need the new API we might just live with not fixing this in v1.11.

**Comment by rzetelskik** [comment]
> that might be a problem, I don't think requiring it retrospectively for v1.11 would be good. if it need the new API we might just live with not fixing this in v1.11.

It definitely requires the 3.2.6 client, but with older version of the server the new fields will just be ignored. Let's not bump the required version for 1.11 then.

**Comment by tnozicka** [comment]
ok, if it's backward compatible we can land it as best effort :+1:

**Comment by tnozicka** [comment]
#1814 landed
/retest

**Pull request merged**
