### PR TITLE
Update Go version to 1.22

### PR DESCRIPTION
**Pull request by rzetelskik**
**Description of your changes:** This PR updates the Go version to 1.22 and accommodates the loopvar fix and ranging over integers introduced in this release.

**Which issue is resolved by this Pull Request:**
Resolves https://github.com/scylladb/scylla-operator/issues/1860

/kind feature
/priority important-soon

### CODE REVIEW

**Review by tnozicka — APPROVED** [review]
/approve
lgtm, thx for taking the time to go over the loops too

/assign @zimnx

**Review by zimnx — APPROVED** [review]
/lgtm

**Comment by rzetelskik** [comment]
https://github.com/scylladb/scylla-operator/issues/1478#issuecomment-2022437025
/test images
/retest

**Comment by tnozicka** [comment]
/hold
you need to bump the CI as well
see https://prow.scylla-operator.scylladb.com/view/gs/scylla-operator-prow/pr-logs/pull/scylladb_scylla-operator/1861/pull-scylla-operator-master-unit/1772754204822081536#1:build-log.txt%3A1

**Comment by tnozicka** [comment]
xref for images fix https://github.com/scylladb/scylla-operator-images/pull/44

**Comment by tnozicka** [comment]
/override ci/prow/e2e-gke-release-script-latest
(shouldn't have been triggered here)

**Pull request merged**
