### PR TITLE
Generate aggregated third-party manifests

### PR DESCRIPTION
**Pull request by tnozicka**
**Description of your changes:**
Aggregating the manifest allows using kubectl -f with remote file.

**Which issue is resolved by this Pull Request:**
Resolves #

/hold
needs https://github.com/scylladb/scylla-operator/pull/1532

### CODE REVIEW

**Comment by tnozicka** [comment]
sound like infra hickup around cloning source code or something
/retest

**Comment by tnozicka** [comment]
/hold cancel
#1532 landed

**Review by rzetelskik — COMMENTED** [review]
lgtm overall, but shouldn't you generate it for local-csi-driver (./examples/common/local-csi-driver/*.yaml to ./examples/common/local-csi-driver.yaml) as well?

**Comment by tnozicka** [comment]
actually, I think that should move to deploy folder (eventually to be gone and managed by nodeconfig) so we can reply on the storage class in your manifest, so it works out of the box

**Comment by rzetelskik** [comment]
> I think that should move to deploy folder (eventually to be gone and managed by nodeconfig) 

The CSI driver is not a hard requirement of ours, only what we recommend for an optimal performance, but there's nothing stopping you from using a different storage provisioner, is there? I can see moving it to `deploy/`, especially as it's not really *third-party*, but I don't really see it as a part of NodeConfig; I guess that's a topic for a separate discussion though. 
My point was that the manifests for the local-csi-driver are also used in our docs so if that's why you want to concatenate the examples then you're going to hit this as well.

**Comment by tnozicka** [comment]
I think it's outside of scope of this PR. It's not a hard requirement but our default setup doesn't work with NVMes without editing the manifest. It should be the other way around.

**Comment by tnozicka** [comment]
thx, I've filled https://github.com/scylladb/scylla-operator/issues/1554 for local-csi-driver

**Comment by rzetelskik** [comment]
https://github.com/scylladb/scylla-operator/issues/1525#issuecomment-1805957503
/test e2e-gke-parallel

**Pull request merged**
