### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by tnozicka**
**Description of your changes:**
Bumps deps together with golang stdlib to make sure we build with CVE fixes.

Go builder was already updated in https://github.com/scylladb/scylla-operator-images/pull/41

**Which issue is resolved by this Pull Request:**
Resolves https://prow.scylla-operator.scylladb.com/view/gs/scylla-operator-prow/logs/ci-scylla-operator-master-govulncheck/1765316610274365440

### CODE REVIEW

**Comment by tnozicka** [comment]
traffic race
/retest

**Comment by rzetelskik** [comment]
Is this going to be backported to 1.12?

**Comment by tnozicka** [comment]
yep, when it lands, I'll backport this to v1.12

/retest
(infra)

**Review by rzetelskik — APPROVED** [review]
/lgtm

**Comment by tnozicka** [comment]
cql traffic
/retest

**Pull request merged**
