### PR TITLE
Set up S3 credentials in e2e machinery

### PR DESCRIPTION
**Pull request by rzetelskik**
**Description of your changes:** As a followup to https://github.com/scylladb/scylla-operator/pull/2050, we need to set up s3 credentials in our e2e machinery.

**Which issue is resolved by this Pull Request:**
Resolves #

/kind feature
/priority important-soon
/cc

### CODE REVIEW

**Review by zimnx — APPROVED** [review]
lgtm
/assign tnozicka

**Review by tnozicka — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
