### PR TITLE
Add a Scylla Manager integration E2E test for error propagation for invalid tasks and invalid updates

### LINKED ISSUE #1907: Extend Scylla Manager integration e2e coverage with error propagation testing
### What should the feature do?

After we will have fixed https://github.com/scylladb/scylla-operator/issues/1752, we should increase Scylla Manager integration e2e coverage with a test verifying task status error propagation.

/priority important-longterm
/kind feature
/assign

### What is the use case behind this feature?

Securing a baseline correctness coverage.

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by rzetelskik**
**Description of your changes:** This PR adds an e2e test covering Scylla Manager task status error propagation for newly created, invalid tasks. The purpose of this is to secure a baseline correctness coverage. It also moves the logic checking error propagation for invalid updates to valid tasks away from the existing e2es to to this one. 

**Which issue is resolved by this Pull Request:**
Resolves #1907

Prerequisites #1850 

/kind feature
/priority important-longterm

### CODE REVIEW

**Comment by rzetelskik** [comment]
/cc zimnx
ready for review

**Review by zimnx — APPROVED** [review]
lgtm
/assign tnozicka

**Review by tnozicka — APPROVED** [review]
/approve
/lgtm

**Comment by rzetelskik** [comment]
Requires https://github.com/scylladb/scylla-operator/pull/1933.

**Comment by rzetelskik** [comment]
Let's have https://github.com/scylladb/scylla-operator/pull/1742 land first since these two share some code.
/hold

**Comment by rzetelskik** [comment]
/cc zimnx
please review, code changed due to https://github.com/scylladb/scylla-operator/pull/1742#discussion_r1606957970

**Review by zimnx — APPROVED** [review]
Thanks for updates.
/lgtm

**Pull request merged**
