### PR TITLE
Update cert-manager example to v1.14.4

### PR DESCRIPTION
**Pull request by tnozicka**
**Description of your changes:**
Updates the cert-manager example to v1.14.4.

Source https://github.com/cert-manager/cert-manager/releases/download/v1.14.0/cert-manager.yaml

### CODE REVIEW

**Review by rzetelskik — COMMENTED** [review]
@tnozicka can you verify you sent all the changes you wanted? It shows up as a deletion and nothing more to me

**Comment by tnozicka** [comment]
ci is about to find (some deletions are old crd versions) but I see `+2,686 −14,007`

**Comment by rzetelskik** [comment]
I guess it's just github diff being weird then.
image
The CI works and the manifest looks sane, so lgtm.
/assign zimnx

**Comment by tnozicka** [comment]
https://github.com/scylladb/scylla-operator/issues/1028#issuecomment-1999808504
/retest

**Comment by tnozicka** [comment]
https://github.com/scylladb/scylla-operator/issues/1767#issuecomment-2003187103
/retest

**Pull request merged**
