### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by tnozicka**
**Description of your changes:**
Updates dependencies to get the latest fixes.

### CODE REVIEW

**Comment by rzetelskik** [comment]
Since you're updating SM client here, I think we can get rid of these two replacements:
```
	github.com/rclone/rclone => github.com/scylladb/rclone v1.54.1-0.20240312172628-afe1fd2aa65e
	google.golang.org/api => github.com/scylladb/google-api-go-client v0.34.1-patched
```

Ref: https://github.com/scylladb/scylla-manager/pull/4010

**Comment by tnozicka** [comment]
remove, thx

**Comment by rzetelskik** [comment]
I suppose the same goes for `github.com/Azure/azure-storage-blob-go`
```sh
$ go mod why -m github.com/Azure/azure-storage-blob-go
# github.com/Azure/azure-storage-blob-go
github.com/scylladb/scylla-operator/pkg/cmd/operator
github.com/scylladb/scylla-manager/v3/pkg/managerclient
github.com/scylladb/scylla-manager/v3/pkg/managerclient.test
github.com/scylladb/scylla-manager/v3/pkg/service/backup
github.com/scylladb/scylla-manager/v3/pkg/scyllaclient
github.com/scylladb/scylla-manager/v3/pkg/rclone/rcserver
github.com/rclone/rclone/backend/azureblob
github.com/Azure/azure-storage-blob-go/azblob
```

**Comment by tnozicka** [comment]
removed as well

**Review by zimnx — APPROVED** [review]
/lgtm

**Comment by tnozicka** [comment]
(clean rebase)

**Pull request merged**
