### PR TITLE
Trap unblocking functions in e2e script's subprocesses

### PR DESCRIPTION
**Pull request by rzetelskik**
**Description of your changes:** This PR traps unblocking functions in both must-gather and artifacts gathering subprocesses in our E2E script. Currently a failure in a subprocess causes it to hang.

/kind machinery
/priority important-longterm
/cc tnozicka

### CODE REVIEW

**Comment by rzetelskik** [comment]
https://github.com/scylladb/scylla-operator/issues/1476#issuecomment-1824232443

**Comment by rzetelskik** [comment]
/test e2e-gke-parallel
https://github.com/scylladb/scylla-operator/issues/1476#issuecomment-1824232443

**Review by tnozicka — APPROVED** [review]
/approve
/lgtm

/hold
when the e2e finishes, link the line where these traps are executed on graceful paths and you are good to go

**Comment by rzetelskik** [comment]
@tnozicka
e2e unblock: https://prow.scylla-operator.scylladb.com/view/gs/scylla-operator-prow/pr-logs/pull/scylladb_scylla-operator/1585/pull-scylla-operator-e2e-gke-parallel/1727644833226428416#1:test-build-log.txt%3A2452
must-gather unblock: https://prow.scylla-operator.scylladb.com/view/gs/scylla-operator-prow/pr-logs/pull/scylladb_scylla-operator/1585/pull-scylla-operator-e2e-gke-parallel/1727644833226428416#1:test-build-log.txt%3A2534

**Comment by tnozicka** [comment]
/hold cancel
thx

**Pull request merged**
