### PR TITLE
[v1.11] Loosen validation for LoadBalancerClass in NodeServiceTemplate

### PR DESCRIPTION
**Pull request by zimnx**
Backport of #1649

### CODE REVIEW

**Review by tnozicka — APPROVED** [review]
/approve
/lgtm

**Comment by zimnx** [comment]
Flake: https://github.com/scylladb/scylla-operator/issues/1525#issuecomment-1864680436
/test e2e-gke-parallel

**Comment by tnozicka** [comment]
/hold
for #1649

**Comment by zimnx** [comment]
#1649 landed
/hold cancel

**Pull request merged**
