### PR TITLE
Remove host networking mentions from documentation and examples

### PR DESCRIPTION
**Pull request by mykaul**
We should not recommend nor support it.
Refs: https://github.com/scylladb/scylla-operator/issues/1378

### CODE REVIEW

**Comment by zimnx** [comment]
/approve

We should also remove it from examples (eks and gke are enabling it)

**Comment by mykaul** [comment]
Added a commit to remove it from the examples. We still have it around in other places, I think these are minor:
```
kaul@ykaul:~/github/scylla-operator$ grep -Frisn hostNetworking
deploy/operator.yaml:1103:                      description: 'port is the port number used to bind the Alternator API. Deprecated: `port` is deprecated and may be ignored in the future. Please make sure to avoid using hostNetworking and work with standard Kubernetes concepts like Services.'
pkg/controller/scyllacluster/resource.go:383:					HostNetwork: c.Spec.Network.HostNetworking,
pkg/api/scylla/v1/scylla.scylladb.com_scyllaclusters.yaml:74:                      description: 'port is the port number used to bind the Alternator API. Deprecated: `port` is deprecated and may be ignored in the future. Please make sure to avoid using hostNetworking and work with standard Kubernetes concepts like Services.'
pkg/api/scylla/v1/scylla.scylladb.com_scyllaclusters.yaml:2049:                    hostNetworking:
pkg/api/scylla/v1/scylla.scylladb.com_scyllaclusters.yaml:2050:                      description: hostNetworking determines if scylla uses the host's network namespace. Setting this option avoids going through Kubernetes SDN and exposes scylla on node's IP.
pkg/api/scylla/v1/types_cluster.go:438:	// hostNetworking determines if scylla uses the host's network namespace. Setting this option
pkg/api/scylla/v1/types_cluster.go:440:	HostNetworking bool `json:"hostNetworking,omitempty"`
pkg/api/scylla/v1/types_cluster.go:577:	// Please make sure to avoid using hostNetworking and work with standard Kubernetes concepts like Services.
docs/source/api-reference/groups/scylla.scylladb.com/scyllaclusters.rst:180:     - port is the port number used to bind the Alternator API. Deprecated: `port` is deprecated and may be ignored in the future. Please make sure to avoid using hostNetworking and work with standard Kubernetes concepts like Services.
docs/source/api-reference/groups/scylla.scylladb.com/scyllaclusters.rst:4564:   * - hostNetworking
docs/source/api-reference/groups/scylla.scylladb.com/scyllaclusters.rst:4566:     - hostNetworking determines if scylla uses the host's network namespace. Setting this option avoids going through Kubernetes SDN and exposes scylla on node's IP.
helm/scylla/values.schema.json:27:          "description": "port is the port number used to bind the Alternator API. Deprecated: `port` is deprecated and may be ignored in the future. Please make sure to avoid using hostNetworking and work with standard Kubernetes concepts like Services.",
helm/scylla/values.schema.json:389:        "hostNetworking": {
helm/scylla/values.schema.json:390:          "description": "hostNetworking determines if scylla uses the host's network namespace. Setting this option avoids going through Kubernetes SDN and exposes scylla on node's IP.",
helm/scylla/values.yaml:37:hostNetworking: false
helm/scylla/templates/scyllacluster.yaml:43:  {{- if .Values.hostNetworking}}
helm/scylla/templates/scyllacluster.yaml:45:    hostNetworking: {{ .Values.hostNetworking }}
helm/scylla-manager/values.schema.json:138:              "description": "port is the port number used to bind the Alternator API. Deprecated: `port` is deprecated and may be ignored in the future. Please make sure to avoid using hostNetworking and work with standard Kubernetes concepts like Services.",
helm/scylla-manager/values.schema.json:500:            "hostNetworking": {
helm/scylla-manager/values.schema.json:501:              "description": "hostNetworking determines if scylla uses the host's network namespace. Setting this option avoids going through Kubernetes SDN and exposes scylla on node's IP.",
enhancements/proposals/1978-scylladbdatacenter-api/README.md:66:- We initially thought that `hostNetworking` helps with performance, but later we discovered we were wrong.
enhancements/proposals/1978-scylladbdatacenter-api/README.md:67:  As we only see the downsides of using it, `hostNetworking` support will be discontinued, and setting it becomes deprecated
```

**Comment by mykaul** [comment]
I assume this should be backported to 1.13 release branch. How do I do it? Manually?

**Comment by zimnx** [comment]
yes, manual backport + PR to `v1.13` branch

**Pull request merged**
