### PR TITLE
[v1.15] Fix graceful termination, early ignition and related tests

### LINKED ISSUE #2244: [v1.15] Backport recent fixes for ignition and container restarts to v1.15
There is a bunch of fixes (some of them still coming) for ignition, restarts, logs and graceful termination, we should also backport them for v1.15. A lot of them and they are connected so backporting them in 1 PR seems reasonable (still individual commits).

### PR list
- [x] #2222 
- [x] #2227 
- [x] #2229 
- [x] #2245
- [x] #2225
- [x] #2246 
- [x] #2212

### PR DESCRIPTION
**Pull request by tnozicka**
**Description of your changes:**
This PR bring in the latest graceful termination and ignition fixes as well as the related tests and debugging options.

- #2222 
- #2227 
- #2229 
- #2245
- #2246 
- #2212 

**Which issue is resolved by this Pull Request:**
Resolves #2244

### CODE REVIEW

**Review by rzetelskik — APPROVED** [review]
lgtm
/assign zimnx

**Comment by zimnx** [comment]
Because PR titles are part of generated changelog, I would avoid having word "Backport" in them. 
Most of the backported PRs are indeed related to graceful termination and ignition, but at least one of them is a feature people might want to see in the changelog (https://github.com/scylladb/scylla-operator/pull/2225). 
Please extract it to separate one and fix naming of this PR to describe what it fixes.

**Comment by tnozicka** [comment]
extracted the loglevel change into https://github.com/scylladb/scylla-operator/pull/2252 and retitled

**Comment by zimnx** [comment]
Thanks!
/lgtm

**Pull request merged**
