### PR TITLE
Support `scyllaArgs` in Helm chart

### PR DESCRIPTION
**Pull request by alexgenco**
**Description of your changes:**

This is copied from https://github.com/scylladb/scylla-operator/pull/1019, which was closed due to inactivity, but I think is still valid.

**Which issue is resolved by this Pull Request:**
Resolves https://github.com/scylladb/scylla-operator/issues/989

### CODE REVIEW

**Review by zimnx — APPROVED** [review]
Thanks for your contribution!

/approve
/lgtm

**Comment by alexgenco** [comment]
Thanks, when can we expect this to get an official release? Looks like the version is 1.12.0

**Comment by zimnx** [comment]
Our release schedule is available here: https://operator.docs.scylladb.com/master/releases.html
Since we are approaching holiday season, it may slip a little.

**Pull request merged**
