### PR TITLE
Collect nodes in must-gather

### LINKED ISSUE #1845: Must-gather should collect Node objects
Nodes objects are important to correctly identify the plarform, CRI, kubelet and related information. It contains information about resources as well.

### PR DESCRIPTION
**Pull request by tnozicka**
**Description of your changes:**
Collection node objects in must-gather helps us to determine the OS, architecture, CRI and more.

**Which issue is resolved by this Pull Request:**
Resolves #1845

### CODE REVIEW

**Comment by tnozicka** [comment]
/retest
https://github.com/scylladb/scylla-operator/issues/1694#issuecomment-2008799441

**Comment by tnozicka** [comment]
disks
/retest

**Review by zimnx — APPROVED** [review]
/lgtm

**Comment by rzetelskik** [comment]
/override ci/prow/e2e-gke-release-script-latest
shouldn't have been triggered

**Comment by rzetelskik** [comment]
@tnozicka could you override ci/prow/e2e-gke-release-script-latest?

**Pull request merged**
