### PR TITLE
Rename Cluster to ScyllaCluster

### PR DESCRIPTION
**Pull request by espindola**

### CODE REVIEW

**Comment by zimnx** [comment]
LGTM, let's wait for 0.3 release before merging this.

**Comment by espindola** [comment]
> LGTM, let's wait for 0.3 release before merging this.

Anything I can do to help with the 0.3 release?

**Comment by zimnx** [comment]
@espindola please rebase the conflicts

**Comment by espindola** [comment]
rebased and pushed.

**Review by zimnx — APPROVED** [review]

**Pull request merged**
