### PR TITLE
member_controller: now using scylla manager agent

### PR DESCRIPTION
**Pull request by dahankzter**
NB: Not hidden behind the agent feature flag. The idea is to release it when the agent docker image
becomes publicly available. 

Fixes: #28

### CODE REVIEW

**Comment by yanniszark** [comment]
@dahankzter nice, however 1654 lines looks kinda wrong.
From the diff I can see that a scylla client is essentially vendored under pkg/scyllaclient.
Isn't there a way to just import the package instead of copying all the source code?

**Comment by dahankzter** [comment]
I tried a lot but I couldn't get `dep` to play nice with some dependent libraries. Once we move to modules I think we can just delete these files and reuse the client generated for mermaid.

**Comment by dahankzter** [comment]
The cluster manager also needs to discover any token the user may have configured.

**Comment by dahankzter** [comment]
Latest commits adds token discovery for the scylla client inside the member controller.

**Comment by yanniszark** [comment]
@dahankzter thanks for the PR!
Can you describe (or point me to some docs) what the scylla manager agent does and if it needs to coordinate with the operator in any way?

Also, I noticed you used a ConfigMap with an auth-token setting inside.
Security-sensitive data should always be in Kubernetes Secrets, never ConfigMaps.
Secrets are handled differently and many environments add extra layers of protection on top of them (think KMS). See: https://kubernetes.io/docs/concepts/configuration/secret/
For starters, we can just place the whole config in a secret instead of a ConfigMap (since it contains security-sensitive information).

It would also greatly help in the review if you could seperate all vendored code in a single commit (without anything else in it).

**Comment by dahankzter** [comment]
Ah of course we should use a secret! Ill amend it here asap.

**Comment by dahankzter** [comment]
I have changed the config to be mounted from a secret instead. What do you think @yanniszark? I am tempted to merge this and patch any smaller changes later.

**Comment by dahankzter** [comment]
Essentially it this docs @yanniszark https://docs.scylladb.com/operating-scylla/manager/2.0/architecture/

**Pull request merged**
