### PR TITLE
Update Scylla Manager version to 3.3.3

### PR DESCRIPTION
**Pull request by rzetelskik**
**Description of your changes:** ~This PR updates the version in our docs, examples and manifests to [3.3.1](https://github.com/scylladb/scylla-manager/releases/tag/v3.3.1), which was tagged today. It also pins the agent version in the examples and manifests.~ ~Edit: 3.3.1 had a regression, so this PR bumps the version to 3.3.2 instead which should fix it.~ Edit: 3.3.2 also had a regression, so it updates the version to 3.3.3

**Which issue is resolved by this Pull Request:**
Resolves #

/kind feature
/priority important-longterm

### CODE REVIEW

**Comment by tnozicka** [comment]
Suspiciously a lot of failed manager tests
```
 Summarizing 3 Failures:
  [FAIL] Scylla Manager integration should register cluster, sync backup tasks and support manual restore procedure [It] using default ScyllaDB version [RequiresObjectStorage]
  github.com/scylladb/scylla-operator/test/e2e/set/scyllacluster/scyllamanager_object_storage.go:146
  [FAIL] Scylla Manager integration should register cluster, sync backup tasks and support manual restore procedure [It] using workaround for consistent_cluster_management for ScyllaDB Enterprise 2024.1.X [RequiresObjectStorage]
  github.com/scylladb/scylla-operator/test/e2e/set/scyllacluster/scyllamanager_object_storage.go:146
  [FAIL] Scylla Manager integration [It] should discover cluster and sync errors for invalid tasks and invalid updates to existing tasks [RequiresObjectStorage]
  github.com/scylladb/scylla-operator/test/e2e/set/scyllacluster/scyllamanager_object_storage.go:684 
```

**Comment by rzetelskik** [comment]
> Suspiciously a lot of failed manager tests
> ```
>  Summarizing 3 Failures:
>   [FAIL] Scylla Manager integration should register cluster, sync backup tasks and support manual restore procedure [It] using default ScyllaDB version [RequiresObjectStorage]
>   github.com/scylladb/scylla-operator/test/e2e/set/scyllacluster/scyllamanager_object_storage.go:146
>   [FAIL] Scylla Manager integration should register cluster, sync backup tasks and support manual restore procedure [It] using workaround for consistent_cluster_management for ScyllaDB Enterprise 2024.1.X [RequiresObjectStorage]
>   github.com/scylladb/scylla-operator/test/e2e/set/scyllacluster/scyllamanager_object_storage.go:146
>   [FAIL] Scylla Manager integration [It] should discover cluster and sync errors for invalid tasks and invalid updates to existing tasks [RequiresObjectStorage]
>   github.com/scylladb/scylla-operator/test/e2e/set/scyllacluster/scyllamanager_object_storage.go:684 
> ```

Yup, I'll have to look into this

**Comment by rzetelskik** [comment]
At this point it looks to me like the same issue we've hit when releng overwrote 3.3.0 tag: https://github.com/scylladb/scylla-operator/pull/2070#issue-2463272915.

All of the tests seems to be failing on syncing tasks.

Example https://prow.scylla-operator.scylladb.com/view/gs/scylla-operator-prow/pr-logs/pull/scylladb_scylla-operator/2089/pull-scylla-operator-master-e2e-gke-parallel/1825980285708144641#1:test-build-log.txt%3A1647:

```yaml
apiVersion: scylla.scylladb.com/v1
kind: ScyllaCluster
metadata:
  name: basic-tpz79
  namespace: e2e-test-scyllacluster-m4t6m-0-kf9mw
status:
  backups:
  - error: 'Post "http://scylla-manager/api/v1/cluster/3ea765e4-4788-4801-94d1-fd40d4cac18e/tasks":
      context deadline exceeded (Client.Timeout exceeded while awaiting headers)'
    name: backup
  managerId: 3ea765e4-4788-4801-94d1-fd40d4cac18e
```

ScyllaDB Manager logs snippet:
```
2024-08-20T19:59:11.459897955Z {"L":"INFO","T":"2024-08-20T19:59:11.459Z","N":"backup","M":"Generating backup target","cluster_id":"3ea765e4-4788-4801-94d1-fd40d4cac18e","_trace_id":"wqeZFFkzTmqHNU6hqI2AlA"}
2024-08-20T19:59:11.630306392Z {"L":"INFO","T":"2024-08-20T19:59:11.464Z","N":"cluster.client","M":"Checking hosts connectivity","hosts":["10.45.225.58"],"_trace_id":"wqeZFFkzTmqHNU6hqI2AlA"}
2024-08-20T19:59:11.630324562Z {"L":"INFO","T":"2024-08-20T19:59:11.465Z","N":"cluster.client","M":"Host check OK","host":"10.45.225.58","_trace_id":"wqeZFFkzTmqHNU6hqI2AlA"}
2024-08-20T19:59:11.630331402Z {"L":"INFO","T":"2024-08-20T19:59:11.465Z","N":"cluster.client","M":"Done checking hosts connectivity","_trace_id":"wqeZFFkzTmqHNU6hqI2AlA"}
2024-08-20T19:59:11.630337342Z {"L":"INFO","T":"2024-08-20T19:59:11.465Z","N":"backup","M":"Checking accessibility of remote locations","_trace_id":"wqeZFFkzTmqHNU6hqI2AlA"}
2024-08-20T19:59:11.920333411Z {"L":"INFO","T":"2024-08-20T19:59:11.920Z","N":"backup","M":"Location check OK","host":"10.45.225.58","location":"gcs:so-c42d9a33-dc98-45d3-bc1b-37134152b877","_trace_id":"wqeZFFkzTmqHNU6hqI2AlA"}
2024-08-20T19:59:11.920349561Z {"L":"INFO","T":"2024-08-20T19:59:11.920Z","N":"backup","M":"Done checking accessibility of remote locations","_trace_id":"wqeZFFkzTmqHNU6hqI2AlA"}
2024-08-20T19:59:11.920354171Z {"L":"INFO","T":"2024-08-20T19:59:11.920Z","N":"cluster","M":"Get session","cluster_id":"3ea765e4-4788-4801-94d1-fd40d4cac18e","_trace_id":"wqeZFFkzTmqHNU6hqI2AlA"}
2024-08-20T19:59:11.920367211Z {"L":"INFO","T":"2024-08-20T19:59:11.920Z","N":"cluster","M":"Creating new Scylla HTTP client","cluster_id":"3ea765e4-4788-4801-94d1-fd40d4cac18e","_trace_id":"wqeZFFkzTmqHNU6hqI2AlA"}
2024-08-20T19:59:11.925837290Z {"L":"INFO","T":"2024-08-20T19:59:11.925Z","N":"cluster.client","M":"Measuring datacenter latencies","dcs":["us-east-1"],"_trace_id":"wqeZFFkzTmqHNU6hqI2AlA"}
2024-08-20T19:59:11.980139476Z {"L":"INFO","T":"2024-08-20T19:59:11.979Z","N":"http","M":"POST /api/v1/cluster/3ea765e4-4788-4801-94d1-fd40d4cac18e/tasks","from":"10.45.225.33:38892","status":500,"bytes":128,"duration":"525ms","error":"create backup target: create units: no keyspace matched criteria","_trace_id":"wqeZFFkzTmqHNU6hqI2AlA"}
...
2024-08-20T19:59:15.882660502Z {"L":"INFO","T":"2024-08-20T19:59:15.873Z","N":"backup","M":"Generating backup target","cluster_id":"3ea765e4-4788-4801-94d1-fd40d4cac18e","_trace_id":"f1Dx9UHcRqC-Kmuj2bIvZw"}
2024-08-20T19:59:15.882664932Z {"L":"INFO","T":"2024-08-20T19:59:15.880Z","N":"cluster.client","M":"Checking hosts connectivity","hosts":["10.45.225.58"],"_trace_id":"f1Dx9UHcRqC-Kmuj2bIvZw"}
2024-08-20T19:59:15.882669242Z {"L":"INFO","T":"2024-08-20T19:59:15.881Z","N":"cluster.client","M":"Host check OK","host":"10.45.225.58","_trace_id":"f1Dx9UHcRqC-Kmuj2bIvZw"}
2024-08-20T19:59:15.882673012Z {"L":"INFO","T":"2024-08-20T19:59:15.881Z","N":"cluster.client","M":"Done checking hosts connectivity","_trace_id":"f1Dx9UHcRqC-Kmuj2bIvZw"}
2024-08-20T19:59:15.882676452Z {"L":"INFO","T":"2024-08-20T19:59:15.881Z","N":"backup","M":"Checking accessibility of remote locations","_trace_id":"f1Dx9UHcRqC-Kmuj2bIvZw"}
2024-08-20T19:59:16.429315241Z {"L":"INFO","T":"2024-08-20T19:59:16.429Z","N":"backup","M":"Location check OK","host":"10.45.225.58","location":"gcs:so-c42d9a33-dc98-45d3-bc1b-37134152b877","_trace_id":"f1Dx9UHcRqC-Kmuj2bIvZw"}
2024-08-20T19:59:16.429429231Z {"L":"INFO","T":"2024-08-20T19:59:16.429Z","N":"backup","M":"Done checking accessibility of remote locations","_trace_id":"f1Dx9UHcRqC-Kmuj2bIvZw"}
2024-08-20T19:59:16.429547601Z {"L":"INFO","T":"2024-08-20T19:59:16.429Z","N":"cluster","M":"Get session","cluster_id":"3ea765e4-4788-4801-94d1-fd40d4cac18e","_trace_id":"f1Dx9UHcRqC-Kmuj2bIvZw"}
2024-08-20T19:59:16.429642821Z {"L":"INFO","T":"2024-08-20T19:59:16.429Z","N":"cluster","M":"Creating new Scylla HTTP client","cluster_id":"3ea765e4-4788-4801-94d1-fd40d4cac18e","_trace_id":"f1Dx9UHcRqC-Kmuj2bIvZw"}
2024-08-20T19:59:16.435372620Z {"L":"INFO","T":"2024-08-20T19:59:16.435Z","N":"cluster.client","M":"Measuring datacenter latencies","dcs":["us-east-1"],"_trace_id":"f1Dx9UHcRqC-Kmuj2bIvZw"}
2024-08-20T19:59:16.481457357Z {"L":"INFO","T":"2024-08-20T19:59:16.481Z","N":"http","M":"POST /api/v1/cluster/3ea765e4-4788-4801-94d1-fd40d4cac18e/tasks","from":"10.45.225.33:51368","status":500,"bytes":128,"duration":"609ms","error":"create backup target: create units: no keyspace matched criteria","_trace_id":"f1Dx9UHcRqC-Kmuj2bIvZw"}
...
2024-08-20T19:59:18.534436572Z {"L":"INFO","T":"2024-08-20T19:59:18.234Z","N":"backup","M":"Generating backup target","cluster_id":"3ea765e4-4788-4801-94d1-fd40d4cac18e","_trace_id":"hitHSwy9RtmbM7TtbqPcNw"}
2024-08-20T19:59:18.534442732Z {"L":"INFO","T":"2024-08-20T19:59:18.249Z","N":"cluster.client","M":"Checking hosts connectivity","hosts":["10.45.225.58"],"_trace_id":"hitHSwy9RtmbM7TtbqPcNw"}
2024-08-20T19:59:18.534460302Z {"L":"INFO","T":"2024-08-20T19:59:18.251Z","N":"cluster.client","M":"Host check OK","host":"10.45.225.58","_trace_id":"hitHSwy9RtmbM7TtbqPcNw"}
2024-08-20T19:59:18.534466422Z {"L":"INFO","T":"2024-08-20T19:59:18.252Z","N":"cluster.client","M":"Done checking hosts connectivity","_trace_id":"hitHSwy9RtmbM7TtbqPcNw"}
2024-08-20T19:59:18.534471892Z {"L":"INFO","T":"2024-08-20T19:59:18.252Z","N":"backup","M":"Checking accessibility of remote locations","_trace_id":"hitHSwy9RtmbM7TtbqPcNw"}
2024-08-20T19:59:18.872944186Z {"L":"INFO","T":"2024-08-20T19:59:18.872Z","N":"backup","M":"Location check OK","host":"10.45.225.58","location":"gcs:so-c42d9a33-dc98-45d3-bc1b-37134152b877","_trace_id":"hitHSwy9RtmbM7TtbqPcNw"}
2024-08-20T19:59:18.872964146Z {"L":"INFO","T":"2024-08-20T19:59:18.872Z","N":"backup","M":"Done checking accessibility of remote locations","_trace_id":"hitHSwy9RtmbM7TtbqPcNw"}
2024-08-20T19:59:18.872971497Z {"L":"INFO","T":"2024-08-20T19:59:18.872Z","N":"cluster","M":"Get session","cluster_id":"3ea765e4-4788-4801-94d1-fd40d4cac18e","_trace_id":"hitHSwy9RtmbM7TtbqPcNw"}
2024-08-20T19:59:18.872977317Z {"L":"INFO","T":"2024-08-20T19:59:18.872Z","N":"cluster","M":"Creating new Scylla HTTP client","cluster_id":"3ea765e4-4788-4801-94d1-fd40d4cac18e","_trace_id":"hitHSwy9RtmbM7TtbqPcNw"}
2024-08-20T19:59:18.902458954Z {"L":"INFO","T":"2024-08-20T19:59:18.894Z","N":"cluster.client","M":"Measuring datacenter latencies","dcs":["us-east-1"],"_trace_id":"hitHSwy9RtmbM7TtbqPcNw"}
2024-08-20T19:59:18.953326000Z {"L":"INFO","T":"2024-08-20T19:59:18.953Z","N":"http","M":"POST /api/v1/cluster/3ea765e4-4788-4801-94d1-fd40d4cac18e/tasks","from":"10.45.225.33:51380","status":500,"bytes":128,"duration":"723ms","error":"create backup target: create units: no keyspace matched criteria","_trace_id":"hitHSwy9RtmbM7TtbqPcNw"}
```

**Comment by rzetelskik** [comment]
Xref: https://github.com/scylladb/scylla-manager/issues/3989

**Comment by rzetelskik** [comment]
Manager throws a segmentation fault

```
2024-09-09T09:03:55.901858409Z panic: runtime error: invalid memory address or nil pointer dereference
2024-09-09T09:03:55.901873239Z [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x11da5ac]
```
https://gcsweb.scylla-operator.scylladb.com/gcs/scylla-operator-prow/pr-logs/pull/scylladb_scylla-operator/2089/pull-scylla-operator-master-e2e-gke-parallel-clusterip/1833059833192910848/artifacts/must-gather/0/namespaces/scylla-manager/pods/scylla-manager-7fb4d59cfc-f5vw8/scylla-manager.previous

**Comment by rzetelskik** [comment]
3.3.3 was released
/hold cancel

**Comment by tnozicka** [comment]
/approve
(lgtm)

/assign @zimnx

**Pull request merged**
