### PR TITLE
Update UBI runtime to 9.5

### PR DESCRIPTION
**Pull request by tnozicka**
**Description of your changes:**
This PR updates the runtime image to UBI 9.5

### CODE REVIEW

**Review by rzetelskik — APPROVED** [review]
/lgtm
thanks

**Comment by tnozicka** [comment]
https://github.com/scylladb/scylla-operator/issues/2096#issuecomment-2498050137
/retest

**Comment by tnozicka** [comment]
https://github.com/scylladb/scylla-operator/issues/2096#issuecomment-2500153714
/retest

**Pull request merged**
