### PR TITLE
Bump docs theme from 1.1 to 1.2

### LINKED ISSUE #963: docs: update theme to 1.2.1
Related issue https://github.com/scylladb/sphinx-scylladb-theme/issues/310

ScyllaDB Sphinx Theme 1.2.1 is now released 🥳 

We’ve added automatic checks for broken links and introduced numerous UI updates.

You can read more about all notable changes [here](https://sphinx-theme.scylladb.com/stable/upgrade/CHANGELOG.html#march-2022).

## Upgrade guide

For most repositories, we are sending pull-requests with new updates. Unfortunately, we cannot do this for this project since the [docs workflows](https://github.com/scylladb/sphinx-scylladb-theme/tree/master/.github/workflows) shared between all projects to build the docs [were highly modified](https://github.com/scylladb/scylla-operator/tree/master/.github/workflows).

> **TIP:** If you modify these workflows in your repository, you will need to maintain the changes. So instead, we recommend you to open an issue / pull-request in the [sphinx-scylladb-theme repository](https://github.com/scylladb/sphinx-scylladb-theme) so that all projects can benefit from the improvements you made.

Here you have resources to help you upgrade the docs toolchain to the latest version:

- [Migrating from 1.1 to 1.2](https://sphinx-theme.scylladb.com/master/upgrade/1-1-to-1-2.html)
- [Example pull-request](https://github.com/scylladb/scylla-monitoring/pull/1709/files)
- [CHANGELOG](https://sphinx-theme.scylladb.com/stable/upgrade/CHANGELOG.html#march-2022)

Do not hesitate to contact me (@dgarcia360 in Slack) if you face any issues during the process.

### PR DESCRIPTION
**Pull request by tnozicka**
**Description of your changes:**
Bumps docs theme from 1.1 to 1.2

**Which issue is resolved by this Pull Request:**
Resolves #963

### CODE REVIEW

**Comment by tnozicka** [comment]
also it doesn't load the webpage `http://localhost:5500/stable`
```
Error response
Error code: 404

Message: File not found.

Error code explanation: HTTPStatus.NOT_FOUND - Nothing matches the given URI.
```

**Comment by tnozicka** [comment]
the errors came from the old branches and the missing serving data was just my bad - it worked for @rzetelskik as well

**Review by rzetelskik — APPROVED** [review]
lgtm

**Review by rzetelskik — DISMISSED** [review]

**Comment by rzetelskik** [comment]
@tnozicka with the backports to v1.6 all warnings are gone now, please rebase and we're good to go

**Review by rzetelskik — APPROVED** [review]

**Pull request merged**
