### PR TITLE
Update release schedule

### PR DESCRIPTION
**Pull request by zimnx**
Updates release schedule for next release according to our sprints.

### CODE REVIEW

**Review by tnozicka — COMMENTED** [review]
thanks for sending this - following on core schedule changes can you please update the cycle to be 2 months?

**Comment by zimnx** [comment]
> following on core schedule changes can you please update the cycle to be 2 months?

I'm not sure what changes you mean. Could you prepare a PR instead?

**Comment by tnozicka** [comment]
np, I can do that

**Comment by zimnx** [comment]
Thanks

**Pull request closed without merging**
