### PR TITLE
feat: supports priorityClassName

### PR DESCRIPTION
**Pull request by Mokto**
**Description of your changes:**
Added priorityClassName to scylladb cluster

### CODE REVIEW

**Comment by Mokto** [comment]
Thanks.

image

I'm not sure how to fix this one.

**Comment by tnozicka** [comment]
> I'm not sure how to fix this one.

It says: *Please run `make update-crds` ...* - what's not working?

**Comment by Mokto** [comment]
Just ran the command but it still fails.

https://github.com/scylladb/scylla-operator/pull/1986/commits/62e68dddaf7e70830627fc618d0567376217d83d

**Pull request closed without merging**
