### PR TITLE
Add 'externalSeeds' support to ScyllaDB Helm chart

### LINKED ISSUE #1484: Scylla Helm chart doesn't support the `externalSeeds` config option
**Describe the bug**
If we set the `externalSeeds` config option in the `Scylla` helm chart then it just gets ignored.
See https://github.com/scylladb/scylla-operator/blob/69f8a3cf/helm/scylla/templates/scyllacluster.yaml
It's handling is just absent there.

**To Reproduce**
1. Deploy latest `v1.11.0-*` scylla-operator
2. Deploy a Scylla cluster using the `Scylla` Helm chart specifying there `externalSeeds` config option.
3. See that it is absent in the appropriate `ScyllaCluster`.

**Expected behavior**
Helm chart should be up-to-date with the features.

**Logs**
Please, provide `kubectl get events`, `kubectl logs -n scylla pod-name` and other relevant information.

**Environment:**
 - Platform: Any
 - Kubernetes version: Any
 - Scylla version: Any
 - Scylla-operator version: e.g.: `v1.11.0-rc.3`

### PR DESCRIPTION
**Pull request by rzetelskik**
**Description of your changes:** This PR adds support for `externalSeeds` to ScyllaDB Helm chart.

**Which issue is resolved by this Pull Request:**
Resolves #1484 

/kind machinery
/priority important-longterm

### CODE REVIEW

**Review by vponomaryov — APPROVED** [review]
LGTM

**Comment by rzetelskik** [comment]
https://github.com/scylladb/scylla-operator/issues/1476#issuecomment-1766870816

/retest

**Review by zimnx — APPROVED** [review]
/lgtm

Schema was updated when this field was added because helm schema is generated from API spec.

**Comment by tnozicka** [comment]
@rzetelskik please send this to v1.11 branch as well

**Pull request merged**
