### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by tnozicka**
**Description of your changes:**
Updates dependencies to latest

**Which issue is resolved by this Pull Request:**
Resolves https://prow.scylla-operator.scylladb.com/view/gs/scylla-operator-prow/logs/ci-scylla-operator-master-govulncheck/1775770856174129152

### CODE REVIEW

**Review by zimnx — APPROVED** [review]
/lgtm

**Comment by tnozicka** [comment]
/retest
(provisioning failure, a spot instance went away around this time)

**Pull request merged**
