### PR TITLE
Unify the use of taints and tolerations in deploy, docs, examples and tests

### PR DESCRIPTION
**Pull request by rzetelskik**
**Description of your changes:** This PR unifies the use of taints and tolerations in our manifests, tests and docs.
All of the workloads requiring storage tolerate `scylla-operator.scylladb.com/dedicated:scyllaclusters:NoSchedule` taint.

/kind cleanup
/priority important-longterm

**Which issue is resolved by this Pull Request:**
Resolves https://github.com/scylladb/scylla-operator/issues/2049

### CODE REVIEW

**Comment by rzetelskik** [comment]
> @rzetelskik: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> 
> Test name	Commit	Details	Required	Rerun command
> ci/prow/e2e-gke-parallel	[1d945d5](https://github.com/scylladb/scylla-operator/commit/1d945d5bd0de86230c60d5e0ff78d800daa0e37c)	[link](https://prow.scylla-operator.scylladb.com/view/gs/scylla-operator-prow/pr-logs/pull/scylladb_scylla-operator/2235/pull-scylla-operator-master-e2e-gke-parallel/1864338058086715392)	true	`/test e2e-gke-parallel`
> [Full PR test history](https://prow.scylla-operator.scylladb.com/pr-history?org=scylladb&repo=scylla-operator&pr=2235). [Your PR dashboard](https://prow.scylla-operator.scylladb.com/pr?query=is:pr+state:open+author:rzetelskik).

manager flake
https://github.com/scylladb/scylla-operator/issues/2185#issuecomment-2519795618

**Comment by rzetelskik** [comment]
> @rzetelskik: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> 
> Test name	Commit	Details	Required	Rerun command
> ci/prow/e2e-gke-parallel-clusterip	[4e03355](https://github.com/scylladb/scylla-operator/commit/4e03355293f77c1eeb72f986d1d7a5687f757238)	[link](https://prow.scylla-operator.scylladb.com/view/gs/scylla-operator-prow/pr-logs/pull/scylladb_scylla-operator/2235/pull-scylla-operator-master-e2e-gke-parallel-clusterip/1864615606427324416)	true	`/test e2e-gke-parallel-clusterip`
> [Full PR test history](https://prow.scylla-operator.scylladb.com/pr-history?org=scylladb&repo=scylla-operator&pr=2235). [Your PR dashboard](https://prow.scylla-operator.scylladb.com/pr?query=is:pr+state:open+author:rzetelskik).

https://github.com/scylladb/scylla-operator/issues/2061#issuecomment-2520026768
manager flake...

**Review by tnozicka — APPROVED** [review]
For a NodeConfig / DaemonSet and NoSchedule we don't actually need them I think but it doesn't hurt.

/approve
/assign @zimnx

**Review by zimnx — APPROVED** [review]
/lgtm

**Comment by rzetelskik** [comment]
@zimnx since ScyllaDBCluster API merged in the meantime, I also added placement to ScyllaDBCluster definition used in e2e tests, ptal

**Comment by rzetelskik** [comment]
> @rzetelskik: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> 
> Test name	Commit	Details	Required	Rerun command
> ci/prow/e2e-gke-serial	[6c6a517](https://github.com/scylladb/scylla-operator/commit/6c6a517fd8f072374c040991878162ca4cd376de)	[link](https://prow.scylla-operator.scylladb.com/view/gs/scylla-operator-prow/pr-logs/pull/scylladb_scylla-operator/2235/pull-scylla-operator-master-e2e-gke-serial/1866901757137784832)	true	`/test e2e-gke-serial`
> ci/prow/e2e-gke-parallel-clusterip	[6c6a517](https://github.com/scylladb/scylla-operator/commit/6c6a517fd8f072374c040991878162ca4cd376de)	[link](https://prow.scylla-operator.scylladb.com/view/gs/scylla-operator-prow/pr-logs/pull/scylladb_scylla-operator/2235/pull-scylla-operator-master-e2e-gke-parallel-clusterip/1866901756324089856)	true	`/test e2e-gke-parallel-clusterip`
> ci/prow/e2e-gke-parallel	[6c6a517](https://github.com/scylladb/scylla-operator/commit/6c6a517fd8f072374c040991878162ca4cd376de)	[link](https://prow.scylla-operator.scylladb.com/view/gs/scylla-operator-prow/pr-logs/pull/scylladb_scylla-operator/2235/pull-scylla-operator-master-e2e-gke-parallel/1866901754268880896)	true	`/test e2e-gke-parallel`
> [Full PR test history](https://prow.scylla-operator.scylladb.com/pr-history?org=scylladb&repo=scylla-operator&pr=2235). [Your PR dashboard](https://prow.scylla-operator.scylladb.com/pr?query=is:pr+state:open+author:rzetelskik).

logs are missing
/retest

**Pull request merged**
