### PR TITLE
Remove makefile check for go version

### PR DESCRIPTION
**Pull request by tnozicka**
**Description of your changes:**
This PR removes makefile check for minimum Golang that is now duplicate to go.mod enforced by Go itself.

### CODE REVIEW

**Review by zimnx — APPROVED** [review]
/lgtm

**Comment by zimnx** [comment]
> Cluster provisioning failed. Exiting. 

/retest

**Review by rzetelskik — APPROVED** [review]
lgtm
@tnozicka please rebase

**Pull request merged**
