### PR TITLE
Add support for service monitors' custom labels in Scylla Helm chart

### LINKED ISSUE #1194: Add support for service monitors' custom labels in Scylla Helm chart
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Allow passing custom labels for serviceMonitors (both scylla manager & scylla cluster) through helm values.

**What is use case behind this feature:**
This is useful when the users have their own custom Prometheus setup with `serviceMonitorSelector` matchLabels are configured.

**Additional Information:**
Nil

### PR DESCRIPTION
**Pull request by TessaIO**
**Description of your changes:**
This PR aims to support custom labels for service monitors created by the Helm chart. This is needed because we only consider Prometheus service monitors with a specific label and currently service monitors created by the Scylla Helm chart don't have any label.

**Which issue is resolved by this Pull Request:**
Resolves #1194

### CODE REVIEW

**Comment by TessaIO** [comment]
@tnozicka can you please take a look at it?

**Comment by TessaIO** [comment]
ping @tnozicka

**Review by zimnx — APPROVED** [review]
thanks, please extract autogenerated changes (schema) to separate commit and rename your commits/PR title to use imperative mood.

**Comment by rzetelskik** [comment]
> @zimnx thx for the review. Commits are split now, but I'm unsure what you mean by imperative mood. I followed the contribution guide anyway. If it doesn't still comply please suggest one

The contribution guide is a bit outdated, @zimnx is working on updating it in https://github.com/scylladb/scylla-operator/pull/2130.
See https://cbea.ms/git-commit/#imperative; the commit subject line and PR title should basically answer `If applied, this commit/PR will` ..., e.g. `Add support for service monitors' custom labels in Scylla Helm chart`.

**Comment by TessaIO** [comment]
@zimnx @rzetelskik thx, please check!

**Comment by rzetelskik** [comment]
@TessaIO thanks, but I only meant that it should answer `If applied, this commit/PR will...`, not include it. :sweat_smile: 
Please change both the PR title and commit subject line to only `Add support for service monitors' custom labels in Scylla Helm chart` and it should be good to go.

/ok-to-test
/priority important-longterm
/kind machinery

**Comment by TessaIO** [comment]
@rzetelskik done!

**Comment by zimnx** [comment]
Looks like you haven't fully updated what's autogenerated. Run `make update` in root dir of repository and squash into autogenerated commit.

**Comment by TessaIO** [comment]
@zimnx can you please take a look?

**Review by zimnx — APPROVED** [review]
/lgtm
Thanks for contribution!

**Pull request merged**
