### PR TITLE
Move aggregated deploy manifests to deploy folder

### LINKED ISSUE #1533: Aggregate manifest for remote deployment
Aggregating all deploy manifests would allows users to do `kubectl apply --server-side -f https://github.com/scylladb/scylla-operator/raw/master/deploy/operator.yaml` that complements the local `kubectl apply --server-side -f deploy/operator/`. For newcomers this is convenient because they don't have to checkout the repo.

### PR DESCRIPTION
**Pull request by tnozicka**
**Description of your changes:**
Aggregating all deploy manifests allows users to do `kubectl apply --server-side -f https://github.com/scylladb/scylla-operator/raw/master/deploy/operator.yaml` that complements the local `kubectl apply --server-side -f deploy/operator/`

Moving the aggregated manifests to deploy folder ensures they can be found and referenced in out install scenarios.

This also add an aggregated version of dev setup for manager. 

Resolves #1533

### CODE REVIEW

**Comment by zimnx** [comment]
We already have these in the repo at `examples/common/operator.yaml` and `examples/common/manager.yaml` (only `-prod` variant) autogenerated by:
https://github.com/scylladb/scylla-operator/blob/bda16e4109a0bd714e9d84fc9a382c906dc61c2f/Makefile#L483
and 
https://github.com/scylladb/scylla-operator/blob/bda16e4109a0bd714e9d84fc9a382c906dc61c2f/Makefile#L493

**Comment by tnozicka** [comment]
good catch, I forgot about those two. I'll move them to the deploy folder (+add the dev variant) and update the docs links

**Comment by tnozicka** [comment]
verify flaked on https://github.com/scylladb/scylla-operator/issues/1546
e2e-gke-parralel on https://github.com/scylladb/scylla-operator/issues/1478
/retest

**Review by zimnx — APPROVED** [review]
/lgtm

**Comment by tnozicka** [comment]
https://github.com/scylladb/scylla-operator/issues/1433
/retest

**Pull request merged**
