### PR TITLE
Use generic pointer.Ptr in entire project

### PR DESCRIPTION
**Pull request by zimnx**
Thanks to generics we can use pointer.Ptr without specifying required type of return value. All usages of previous typed functions were changed to use the generic one.

### CODE REVIEW

**Comment by zimnx** [comment]
Failure is unrelated to this PR.

/override ci/prow/unit

**Review by tnozicka — APPROVED** [review]
/approve
/lgtm

**Comment by tnozicka** [comment]
/retest
autoscaler picked this node for scale down :(

**Pull request merged**
