### PR TITLE
Supports ipv6

### PR DESCRIPTION
**Pull request by Mokto**
# Description of your changes:
Supports ipv6 addresses. I assume that there is more to be done on this PR (make it conditional maybe?) so we can merge it. I would appreciate you guide me in the right direction.

It did work on my ipv6 cluster though.

Thanks!

# Which issue is resolved by this Pull Request:
Resolves https://github.com/scylladb/scylla-operator/issues/1206

### CODE REVIEW

**Comment by Mokto** [comment]
I'm reopening this one, after rebasing the branch.

Hopefully the tests will pass.

**Comment by Mokto** [comment]
Up

**Comment by Mokto** [comment]
Not stale.

**Comment by rzetelskik** [comment]
/ok-to-test
As @tnozicka already said on the previous PR, this needs to be wired consistently and tested to claim it actually adds ipv6 support: https://github.com/scylladb/scylla-operator/pull/1973#issuecomment-2173429009. See notes on https://github.com/scylladb/scylla-operator/issues/1206 for details.
There are also outstanding merge commits which we don't allow.

**Pull request closed without merging**
