### PR TITLE
Update actions in CI

### LINKED ISSUE #1063: Deprecated actions in our CI
CI jobs are issuing a warning about deprecated actions:
 
```
--
Node.js 12 actions are deprecated. For more information see: 
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. 
Please update the following actions to use Node.js 16: actions/checkout, actions/setup-go, actions/upload-artifact, actions/checkout
 ```

### PR DESCRIPTION
**Pull request by Choraden**
**Description of your changes:**
This PR will update actions in our CI, as some of them were deprecated.

**Which issue is resolved by this Pull Request:**
Resolves #1063

### CODE REVIEW

**Comment by zimnx** [comment]
There're still 2 warnings in CI about deprecated packages.

**Comment by Choraden** [comment]
True. Looks like dependabot didn't catch them. 
Thanks!

**Review by zimnx — DISMISSED** [review]
Please update the PR with bumping version on more deprecated actions.

**Comment by Choraden** [comment]
@zimnx done

**Review by tnozicka — APPROVED** [review]
/approve
/lgtm

thanks!

**Pull request merged**
