### PR TITLE
Remove support for deprecated `cpuset` field

### LINKED ISSUE #2140: Remove support for deprecated cpuset field
### What should the feature do?

Remove support for cpuset field, assuming it's always set to true regardless of value set.

### What is the use case behind this feature?

This field gives misleading feeling that it enables cpupinning which on Kubernetes is handled differently than on baremetals. Instead having a knob for it, Operator should set allowed cpus always.

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by zimnx**
It is now treated as if it is always set to true regardless of its value.
Validation of ScyllaCluster resources is relaxed to not require full cores and resource requests == limits.
Conditions for getting Guaranteed QoS class are explained in documentation.

Fixes #2140

### CODE REVIEW

**Review by tnozicka — COMMENTED** [review]
> It is now treated as if it is always set to true regardless of its value.

This should be reflected in the API comment as well, otherwise this lgtm

**Review by rzetelskik — APPROVED** [review]
lgtm
/assign tnozicka

**Comment by zimnx** [comment]
> This should be reflected in the API comment as well, otherwise this lgtm

done

**Pull request merged**
