### PR TITLE
Remove pre-rollout check validating ScyllaDB version

### LINKED ISSUE #2034: Remove pre-rollout check validating if Scylla supports HostID based node replacement
### What should the feature do?

We should get rid of pre-rollout check validating minimal ScyllaDB version <5.2.0 and <2023.1.0 when they are no longer supported.

EOL claim for 2022.1 can be found in [2024.1 release notes](https://forum.scylladb.com/t/scylladb-enterprise-release-2024-1-0/1292) and 5.1 is not mentioned as supported in [6.0 release notes](https://forum.scylladb.com/t/release-scylladb-6-0/2143).

### What is the use case behind this feature?

Reduce tech debt

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by zimnx**
**Description of your changes:**

Minimal versions which this check validated are already EOL, and we don't claim we support them in our documentation.

**Which issue is resolved by this Pull Request:**
Resolves #2034

### CODE REVIEW

**Review by tnozicka — COMMENTED** [review]
shouldn't you remove this as well?
https://github.com/scylladb/scylla-operator/blob/eb144ac50175c040e486f47eb9468908181ce678/pkg/scyllafeatures/scyllafeatures.go#L33-L37
https://github.com/scylladb/scylla-operator/blob/eb144ac50175c040e486f47eb9468908181ce678/pkg/scyllafeatures/scyllafeatures.go#L20

**Comment by zimnx** [comment]
> shouldn't you remove this as well?

yep, removed.

**Review by rzetelskik — APPROVED** [review]
lgtm
/assign tnozicka

**Review by tnozicka — APPROVED** [review]
/approve
/lgtm
thanks

**Pull request merged**
