### PR TITLE
Add zendesk tag for docs

### PR DESCRIPTION
**Pull request by dgarcia360**
Related: https://github.com/scylladb/sphinx-scylladb-theme/pull/979

Adds the Zendesk validation tag to the docs site.

## How to test

1. Run `make multiversion`.
1. Open the `_build/dirhtml/index.html` file.
1. Check for the presence of the Zendesk tag associated with this project.

### CODE REVIEW

**Comment by dgarcia360** [comment]
cc/ @annastuchlik

**Comment by dgarcia360** [comment]
@rzetelskik Fixed

**Comment by rzetelskik** [comment]
Thanks David!
/lgtm

**Review by tnozicka — APPROVED** [review]
/approve
/lgtm

thanks!

**Pull request merged**
