### PR TITLE
Unify waiting for object state

### PR DESCRIPTION
**Pull request by tnozicka**
**Description of your changes:**
This PR unifies the methods we have for waiting for object state and replaces some that did it manually.

### CODE REVIEW

**Comment by tnozicka** [comment]
GKE cluster didn't start 
/shrug
/retest

**Comment by tnozicka** [comment]
@rzetelskik gentle ping

**Review by rzetelskik — APPROVED** [review]
/lgtm
thanks!

**Comment by tnozicka** [comment]
/retest
(cluster issues + possible drain)

**Pull request merged**
