### PR TITLE
Docs: Update Sphinx theme to v1x

### PR DESCRIPTION
**Pull request by lauranovich**
Upgrades the Scylla Theme to v1.x
This change does not include any HP fixes or any other issues which will be handled with additional PRs. Please merge this FIRST.

**Description of your changes:**

**Which issue is resolved by this Pull Request:**
Resolves #

### CODE REVIEW

**Comment by lauranovich** [comment]
@dgarcia360 please take a look - the build has an error - works locally

**Comment by lauranovich** [comment]
The following error has been noted

/home/lauranovich/github-repo/laura-operator/docs/source/migration.md: WARNING: document isn't included in any toctree
/home/lauranovich/github-repo/laura-operator/docs/source/nodeoperations/automatic_cleanup.md: WARNING: document isn't included in any toctree
/home/lauranovich/github-repo/laura-operator/docs/source/nodeoperations/maintenance_mode.md: WARNING: document isn't included in any toctree
/home/lauranovich/github-repo/laura-operator/docs/source/nodeoperations/replace_node.md: WARNING: document isn't included in any toctree
/home/lauranovich/github-repo/laura-operator/docs/source/nodeoperations/restore.md: WARNING: document isn't included in any toctree
/home/lauranovich/github-repo/laura-operator/docs/source/nodeoperations/scylla_upgrade.md: WARNING: document isn't included in any toctree

**Comment by tzach** [comment]
@lauranovich are these warning a regression ?

**Comment by lauranovich** [comment]
@tzach they were there before - it wasn't caused by the upgrade

**Review by tzach — APPROVED** [review]
LGTM

**Comment by dgarcia360** [comment]
Looks good to me. Since the repo is open-source, we could also enable the ["Edit on GitHub" button](https://sphinx-theme.scylladb.com/stable/configuration/template.html#contribute-button-options).

**Comment by tnozicka** [comment]
do we need the version suffixes in file names?

**Comment by dgarcia360** [comment]
Many thanks @tnozicka @zimnx for the feedback!

We are going to add some of your suggestions to the [Scylla Sphinx Theme](https://github.com/scylladb/sphinx-scylladb-theme/tree/master/.github/workflows) repository.

> do we need the version suffixes in workflow's file names?

We are adding these workflows to many projects. Versioning helps us know which version of the file each project is using.

**Comment by tzach** [comment]
@dgarcia360 what is the next step for this PR?

**Pull request closed without merging**
