### PR TITLE
Switch runtime image to the new UBI base image

### LINKED ISSUE #1192: Move to ubi-minimal images
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
The ubuntu base images have unnecessary packages and contain CVEs, We should move our runtime images to `registry.access.redhat.com/ubi9/ubi-minimal` that has much lover attach surface and is well maintained.

**What is use case behind this feature:**
Security

**Additional Information:**
Needs to make a new set of base images built in scylla-operator-images repo. ( https://github.com/scylladb/scylla-operator-images/issues/13 )

### PR DESCRIPTION
**Pull request by tnozicka**
**Description of your changes:**
We have stopped building Ubuntu base images in https://github.com/scylladb/scylla-operator-images/pull/54 and replaced the with UBI. This PR follows up on that effort and switches the runtime image to UBI.

**Which issue is resolved by this Pull Request:**
Resolves #1192 

fyi @ylebi 

### Requires
- [x] https://github.com/scylladb/scylla-operator-images/issues/67
- [x] https://github.com/scylladb/scylla-operator-images/pull/73
- [x] https://github.com/scylladb/scylla-operator-images/pull/75

### CODE REVIEW

**Comment by tnozicka** [comment]
blocked on https://github.com/scylladb/scylla-operator-images/issues/66

**Comment by tnozicka** [comment]
`find` is missing - https://github.com/scylladb/scylla-operator-images/pull/73

**Comment by tnozicka** [comment]
https://github.com/scylladb/scylla-operator-images/pull/73 has landed
/retest

**Comment by tnozicka** [comment]
`mount` is missing - https://github.com/scylladb/scylla-operator-images/pull/75

**Comment by tnozicka** [comment]
https://github.com/scylladb/scylla-operator-images/pull/75 landed
/test images

**Comment by tnozicka** [comment]
all green now, ptal

**Review by rzetelskik — APPROVED** [review]
/lgtm
Thanks!

**Pull request merged**
