### PR TITLE
Update Scylla Manager to 3.2.7

### PR DESCRIPTION
**Pull request by rzetelskik**
**Description of your changes:**
This PR updates Scylla Manager version in our manifests to 3.2.7. Most notably it fixes https://github.com/scylladb/scylla-manager/issues/3769.

**Which issue is resolved by this Pull Request:**
Resolves #

/kind feature
/priority important-longterm

### CODE REVIEW

**Comment by rzetelskik** [comment]
Manager client is being updated in https://github.com/scylladb/scylla-operator/pull/1877.

**Review by tnozicka — COMMENTED** [review]
missing `examples/scylladb/scylla.scyllacluster.yaml:6:  agentVersion: 3.2.6`

**Comment by rzetelskik** [comment]
> missing examples/scylladb/scylla.scyllacluster.yaml:6:  agentVersion: 3.2.6

fixed, thanks

**Comment by rzetelskik** [comment]
flake https://github.com/scylladb/scylla-operator/issues/1028#issuecomment-2037124956
/retest

**Comment by rzetelskik** [comment]
> @rzetelskik: The following test failed, say /retest to rerun all failed tests or /retest-required to rerun all mandatory failed tests:
> 
> Test name	Commit	Details	Required	Rerun command
> ci/prow/e2e-gke-parallel-clusterip	https://github.com/scylladb/scylla-operator/commit/662eda2ff7f07514c99ffa5a1d97cfe8cec57110	[link](https://prow.scylla-operator.scylladb.com/view/gs/scylla-operator-prow/pr-logs/pull/scylladb_scylla-operator/1880/pull-scylla-operator-master-e2e-gke-parallel-clusterip/1775908014201507840)	unknown	/test e2e-gke-parallel-clusterip
> [Full PR test history](https://prow.scylla-operator.scylladb.com/pr-history?org=scylladb&repo=scylla-operator&pr=1880). [Your PR dashboard](https://prow.scylla-operator.scylladb.com/pr?query=is:pr+state:open+author:rzetelskik).
> 

Manager flake https://github.com/scylladb/scylla-operator/issues/1694, second time on this PR.

Test got stuck on waiting for repair task deletion: https://prow.scylla-operator.scylladb.com/view/gs/scylla-operator-prow/pr-logs/pull/scylladb_scylla-operator/1880/pull-scylla-operator-master-e2e-gke-parallel-clusterip/1775908014201507840#1:test-build-log.txt%3A1165.

I can see that the controller sent a request for task deletion:
```
2024-04-04T15:51:10.724078650Z I0404 15:51:10.590055       1 manager/sync.go:134] "Executing action" action="delete ta
sk \"cc49e122-0879-4e00-b6d0-68f67a0ec31f\""
```

Yet the task was never deleted from status. Looks like a controller bug, but the manager logs rolled, so I have no way of confirming that, and no way of verifying whether this update doesn't introduce regressions.

I don't think this should be merged until the manager controller reaches a tolerable stability.
/hold

**Comment by tnozicka** [comment]
> but the manager logs rolled

why didn't we collect the "previous" logs? (we should)

**Comment by rzetelskik** [comment]
> why didn't we collect the "previous" logs? (we should)

previous logs are there, but current must have been trimmed.

```sh
$ cat artifacts/must-gather/namespaces/scylla-manager/pods/scylla-manager-controller-56bbb6b9b4-5q4mw/scylla-manager-controller.current | grep -e 'delete task \\"cc49e122-0879-4e00-b6d0-68f67a0ec31f\\"'
2024-04-04T15:51:10.724078650Z I0404 15:51:10.590055       1 manager/sync.go:134] "Executing action" action="delete task \"cc49e122-0879-4e00-b6d0-68f67a0ec31f\""
```
```sh
cat artifacts/must-gather/namespaces/scylla-manager/pods/scylla-manager-55596764c-5phf6/scylla-manager.current | sed -e 1b -e '$!d' | sed -e 's/\s.*$//'
2024-04-04T16:10:14.087323257Z
2024-04-04T16:17:58.071577325Z
```
```sh
cat artifacts/must-gather/namespaces/scylla-manager/pods/scylla-manager-55596764c-5phf6/scylla-manager.previous | sed -e 1b -e '$!d' | sed -e 's/\s.*$//'
2024-04-04T15:42:33.183142643Z
2024-04-04T15:44:33.866142243Z
```

**Pull request merged**
